### ISSUE TITLE
/api/users return all users and passwords

### ISSUE THREAD

**Issue by meriororen** [berkedel/liqo-js#1]
Should only return current user, or better idea?

**Comment by berkedel** [comment]
`/api/users` should return all recorded users. In order to obtain current user, maybe we can query a request like `/api/users/me` right? Found out [this link](https://parseplatform.github.io/docs/rest/guide/#users) for inspiration.

**Comment by meriororen** [comment]
ok then.

this may be reopened if we already consider user role (or security feature)
