### ISSUE TITLE
request: auth expiry in httpresponse

### ISSUE THREAD

**Issue by meriororen** [berkedel/liqo-js#3]
please put auth expiration time in http response when doing a login.

e.g. 

{ status code: 200, headers {
    ....
    Connection = "Keep-Alive";
    Date = "Thu, 23 Jul 2015 10:47:56 GMT";
    "Keep-Alive" = "timeout=5, max=100";
    Server = Apache;
    ...
} }

**Comment by berkedel** [comment]
For what purpose do you intend to use? When you request with expired token, you'll get a response below

```
HTTP/1.1 401 Unauthorized
Content-Type: text/plain; charset=utf-8
Content-Length: 14
Date: Wed, 21 Sep 2016 12:55:57 GMT
Connection: keep-alive

Invalid token
```

**Comment by meriororen** [comment]
To manage tokens in client-side database. 
So I know if token is already invalid _before_ I do a http request. 
e.g. to decide whether to show login view or main view

this should be low priority issue tho

**Comment by meriororen** [comment]
Done.
